name: Test Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.2
      - name: Set up virtualenv and install dependencies
        run: |
            make venv
            make install-dev
            make update-venv
      - name: Run tests
        run: make coverage
